version: '3.7'
services:

  conjur-db:
    image: postgres:12
    environment:
      POSTGRES_DB: conjur
      POSTGRES_USER: conjur
      POSTGRES_PASSWORD: conjur
    volumes:
      - conjur-data:/var/lib/postgresql/data

  conjur:
    image: cyberark/conjur
    depends_on: [conjur-db]
    ports: ["8080:8080"]
    environment:
      DATABASE_URL: "jdbc:postgresql://conjur-db/conjur"
      DATABASE_USERNAME: conjur
      DATABASE_PASSWORD: conjur
      CONJUR_DATA_KEY: abc123CONJUR_DATA_KEY

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: appdb
      MYSQL_USER: appuser
      MYSQL_PASSWORD: will-be-set-by-conjur
      MYSQL_ROOT_PASSWORD: rootpwd
    ports: ["3306:3306"]
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5

  web:
    build: ../webapp
    depends_on: [conjur, mysql]
    ports: ["3000:3000"]
    environment:
      - CONJUR_ACCOUNT
      - CONJUR_APPLIANCE_URL
      - CONJUR_AUTHN_LOGIN
      - CONJUR_AUTHN_API_KEY
      - DB_HOST=mysql
      - DB_USER=appuser
      - DB_NAME=appdb

volumes:
  conjur-data:
